### ISSUE TITLE
Create topology-specific configurations for both Mininet and the controller

### ISSUE THREAD

**Issue by ecklm** [ecklm/adaptive-network-slicing#2]
Ideally, at least one more switch and one more host should be added to the topology.

**Comment by ecklm** [comment]
Originally I created a custom topology to the scenario due to the hardwired values relating to switch ports. Now that those have been eliminated in #1, the simple scenarios can simply be produced with different builtin topologies of `mininet` such as `linear,x,y` or `tree,x,y`.

**Comment by ecklm** [comment]
b61f3d3968ff85059b0ce9310264da4e8ad4e021 is also relevant

**Comment by ecklm** [comment]
Basics are now implemented, more complicated flow setup is to be set up later if necessary.

A possible setup
```yaml
---
## Mandatory values
flows:
  # f1,2: A -> UE1
  - ipv4_dst: 10.0.0.11
    udp_dst: 5001
    base_ratelimit: 5000000 # 5Mbps
  - ipv4_dst: 10.0.0.11
    udp_dst: 5003
    base_ratelimit: 15000000 # 15 Mbps

  # f3,4: A -> UE3
  - ipv4_dst: 10.0.0.13
    udp_dst: 5001
    base_ratelimit: 5000000 # 5Mbps
  - ipv4_dst: 10.0.0.13
    udp_dst: 5003
    base_ratelimit: 15000000 # 15 Mbps

  # f5: A -> UE2
  - ipv4_dst: 10.0.0.12
    udp_dst: 5002
    base_ratelimit: 25000000 # 25 Mbps

```
