### ISSUE TITLE
Controller: Integrate some configuration parser

### ISSUE THREAD

**Issue by ecklm** [ecklm/adaptive-network-slicing#4]
A config file format should be selected and its parsing implemented in the controller.
Preferably YAML or INI.

As a first step, extract parameters such as `time_step`, `QoSManager.LIMIT_STEP` and others which do not require touching the internals of classes.

**Comment by ecklm** [comment]
Check out config file formats support for python3

- [x] YAML
- [x] INI

**Comment by ecklm** [comment]
- INI-like [configparser](https://docs.python.org/3/library/configparser.html)
  - Supports default values
  - Sections (not sure if necessary here)
  - Support for [value interpolation](https://docs.python.org/3/library/configparser.html#interpolation-of-values) = using keys as variables inside the config file
- [PyYAML](https://pyyaml.org/wiki/PyYAMLDocumentation)
  - Not specific to configurations
  - Supports complex data types (lists, dictionaries)
  - Support for direct creation of python objects (extendable) -- may be good for reading `FlowId` objects
  - Supports aliases ~ object-level variable substitution
  - Supports tags ~ type hints

**Comment by ecklm** [comment]
PyYaml object creation __should not be used__ as it can create non-conforming objects with the same class name enabling mistyped names in the config. See how the mix of `udp_dst` and `upd_dst` in the output gets parsed without any error.

#### util.py
```python3
@dataclass(frozen=True)
class FlowId:
    ipv4_dst: str
    udp_dst: int

    def __repr__(self):
        return self.__str__()

    def __str__(self):
        return str(self.__dict__)
```

#### config.yml
```yaml
---
flows:
  - !!python/object:util.FlowId
    ipv4_dst: 192.0.2.1
    upd_dst: 5001
  - !!python/object:util.FlowId
    ipv4_dst: 192.0.2.2
    udp_dst: 5002
  - !!python/object:util.FlowId
    ipv4_dst: 192.0.2.3
    udp_dst: 5003
  - !!python/object:util.FlowId
    ipv4_dst: 192.0.2.4
    udp_dst: 5004
  - ipv4_dst: 192.0.2.5
    udp_dst: 5005
```

#### Python console
```python3
>>> import yaml
>>> from yaml import Loader, Dumper
>>> with open('config.yml', 'r') as f:
...     o = yaml.load(f, Loader=Loader)
...     
>>> print(o)
{'flows': [{'ipv4_dst': '192.0.2.1', 'upd_dst': 5001}, {'ipv4_dst': '192.0.2.2', 'udp_dst': 5002}, {'ipv4_dst': '192.0.2.3', 'udp_dst': 5003}, {'ipv4_dst': '192.0.2.4', 'udp_dst': 5004}, {'ipv4_dst': '192.0.2.5', 'udp_dst': 5005}]}

```
